// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhglVPulKTNsMxFYvP-N7kdGWkCntmarE',
    appId: '1:820267554232:web:700569a041c3097c592b4d',
    messagingSenderId: '820267554232',
    projectId: 'quizzle-41a04',
    authDomain: 'quizzle-41a04.firebaseapp.com',
    storageBucket: 'quizzle-41a04.appspot.com',
    measurementId: 'G-VXF9BCJRDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Ta7MLsi2plvzrsGmSEkKpwvEL5qTjrM',
    appId: '1:820267554232:android:ce71b1a6fca6d348592b4d',
    messagingSenderId: '820267554232',
    projectId: 'quizzle-41a04',
    storageBucket: 'quizzle-41a04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb7xYrn7RR6PZfnK7--FH_J972Y-XzbdI',
    appId: '1:820267554232:ios:c060b29300e8bece592b4d',
    messagingSenderId: '820267554232',
    projectId: 'quizzle-41a04',
    storageBucket: 'quizzle-41a04.appspot.com',
    iosClientId: '820267554232-t3ua5mko1ipugobi09nn2o39auodvmqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb7xYrn7RR6PZfnK7--FH_J972Y-XzbdI',
    appId: '1:820267554232:ios:c060b29300e8bece592b4d',
    messagingSenderId: '820267554232',
    projectId: 'quizzle-41a04',
    storageBucket: 'quizzle-41a04.appspot.com',
    iosClientId: '820267554232-t3ua5mko1ipugobi09nn2o39auodvmqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );
}
